version: '3.1'

services:

  mongo:
      image: mongo:5
      container_name: mongo-db
      restart: always
      volumes:
        - ./file-json:/file-json
        - ./db:/data/db
      ports:
        - 8081:27017